version: '3.9'

services:
    app:
        image: milaymaxell/upcsg
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
        command: ['npm', 'run', 'start']
